services:
  - type: web
    name: quantumdesk-backend
    env: node
    plan: free
    region: frankfurt
    branch: main
    buildCommand: "npm install"
    startCommand: "node src/server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
